### PR TITLE
[WIP] Add support for .top force field to MolecularForceField constructor

### PR DESCRIPTION
**Pull request by bondrewd**
This PR adds support for parsing Gromacs `.top` and `.itp` files and refactors the MolecularForceField constructor to enable initializing systems using force fields and topologies in Gromacs format.

### CODE REVIEW

**Comment by bondrewd** [comment]
@jgreener64 After implementing the `.top` parser, I found refactoring the current MolecularForceField structure is necessary. Currently, it is specific to OpenMM force fields, fixing the types of some interactions (PeriodicTorsion for dihedrals). I suggest making the MolecularForceField more general, allowing the representation of all the interactions currently supported in Molly. For example, right now RBTorsionTypes cannot be represented.

Regarding the Gromacs `.top` parser, it is done. I added it to a new file names `parsers.jl` to avoid cluttering the `setup.jl` file. It supports the preprocessor directives `#include`, `#define`, `#ifdef`, `#ifndef`, `#else`, and `#endif`. The only change that I will add that came to my head while writing this is support for uppercase and mix-case directives since, for example, "[ atoms ]" and "[ ATOMS ]" are both valid. The parser is still far from optimal, but optimizing it can be pushed into the future.

My next step for completing this PR will be refactoring the MolecularForceField structure to increase its representativity of the current interactions implemented in Molly.

**Comment by ejmeitz** [comment]
Hey,

I've been trying to re-write some code so that Molly is more strict on what units you're allowed to use. One of the latest issues I ran into was actually with the MolecularForceField constructor. Specifically, I am trying to limit the mixture of molar and non-molar quantities. At the moment the default units use `u` for mass and `kJ/mol` for energy which is of course mixing molar and non-molar. Are these units standard for whatever file is being parsed here? Mixing units like this causes major issues down the line with Unitful and the branch I have open currently won't let you construct a `System` with this type of units. How should I change this part of the code to ameliorate this?

Specifically this code:
```julia
if units
        M = typeof(T(1u"u"))
        D = typeof(T(1u"nm"))
        E = typeof(T(1u"kJ * mol^-1"))
        K = typeof(T(1u"kJ * mol^-1 * nm^-2"))
    else
        M, D, E, K = T, T, T, T
    end
```

**Comment by bondrewd** [comment]
@ejmeitz Hi!

I think there are more places where masses are parsed as numbers with the `u"u"` unit:

https://github.com/JuliaMolSim/Molly.jl/blob/e353dfbd444e2ac4ea05c4aae0b58b3658815445/src/setup.jl#L211

One solution would be to add an argument in the constructor for the mass type and set `u"g/mol"` as the default value `constructor(... ; ..., M=u"g/mol", ...)`.

**Comment by bondrewd** [comment]
@ejmeitz As for the standard mass units, it depends on the force field. For example, in Gromacs, the mass unit in the `.top` files [is defined as `u"u"`](https://manual.gromacs.org/documentation/2019/reference-manual/definitions.html).

**Comment by ejmeitz** [comment]
Cool thanks for the details. I guess I could also auto-convert `u` into `g/mol` after the parsing since they're basically identical. I wonder if Gromacs assumes `1u = 1g/mol` internally or if they deal with all the stupid conversions.

That said, looking at your changes I probably can't add this feature to my branch without having a conflict with the changes you're adding.

**Comment by jgreener64** [comment]
Looks good so far.

> I suggest making the MolecularForceField more general, allowing the representation of all the interactions currently supported in Molly

Yes I agree.

I think units should probably change from `u` to `g/mol` throughout the whole package and docs, but that discussion (#140) can take place separate from this PR which can be rebased later if need be.

**Comment by bondrewd** [comment]
This weekend I made the `.top` parser type stable. I am refactoring the `MolecularForceField` structure, constructor, and the `System` constructor using a `MolecularForceField` the following week.

@jgreener64 I would like to include a `.top` and a `.itp` as input for some integration tests (since the code coverage is failing). I can think of three options:
- Add the content as raw strings in the `/test/parser.jl` file
- Add the `.top` and `.itp` files for testing in the `/data/` directory
- Add the `.top` and `.itp` files for testing in a new directory: `/test/data/`
Is any of these ok? Or would you happen to have another idea?

**Comment by jgreener64** [comment]
Sounds like good progress.

I would add them to `data` for now. Strings of only a few lines can go in the test file directly.

**Pull request closed without merging**
