### PR TITLE
add Molly logo

### PR DESCRIPTION
**Pull request by LegionAtol**
The .png and .svg Molly logo as discussed in issue #101

### CODE REVIEW

**Comment by jgreener64** [comment]
The PNG looks great. I can't seem to open the SVG as a vector graphic in something like Inkscape though, am I missing something?

**Comment by LegionAtol** [comment]
I generated the .svg from the .png with an online tool to have it as similar as possible, then I tried to import it into Canva(online tool) and it displayed it correctly, so I thought that if it were to be used within websites or online it would be displayed correctly.
I hadn't tried opening it with vector graphics programs but if needed I can recreate it from scratch with one of these programs

**Comment by jgreener64** [comment]
How did you generate it in the first place, is it possible to save as SVG from there? Ideally we would have a vectorised form to allow us to resize without pixelation.

**Comment by LegionAtol** [comment]
I created the png with Procreate (iPad) and it doesn't allow you to export the work to svg.
So I think there are two options: either I convert the png to svg with an online tool (as I did) or I create it from scratch with a vector graphics program trying to make it identical.
let me know if you have any other ideas

**Comment by jgreener64** [comment]
I think we do want a vector version. Sorry as it is more work.

**Comment by jgreener64** [comment]
Great, thanks for doing this. I will add it to the readme.

**Pull request merged**
